# Generated by Django 6.0.2 on 2026-04-28 05:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkr', '0002_post_dosh_post_wind_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
